# Generated by `nix run .#update`; do not edit.
{
  releases = {
    "0.14.1" = {
      version = "0.14.1";
      date = "2025-05-21";
      hash = "sha256-jhu2NTK6InJfCkpF5cKSCor1CNjKgeYAfDMO7CtwM6Y=";
      url = "https://ziglang.org/download/0.14.1/zig-s390x-linux-0.14.1.tar.xz";
    };
    "0.15.1" = {
      version = "0.15.1";
      date = "2025-08-19";
      hash = "sha256-vNE+XIjPLQ2nEApIVyGVVgBpqUQCyb7DsxY5ggSqJ+I=";
      url = "https://ziglang.org/download/0.15.1/zig-s390x-linux-0.15.1.tar.xz";
    };
    "0.15.2" = {
      version = "0.15.2";
      date = "2025-10-11";
      hash = "sha256-zUspX0Oxt8o9YDNoyuqC29APzmaRr/t1J+YHwLbq/o4=";
      url = "https://ziglang.org/download/0.15.2/zig-s390x-linux-0.15.2.tar.xz";
    };
    "0.16.0" = {
      version = "0.16.0";
      date = "2026-04-13";
      hash = "sha256-FNtIhLMUFL1jeHkDbB5uM187pEzKxZ3xBBY3KKDKsw4=";
      url = "https://ziglang.org/download/0.16.0/zig-s390x-linux-0.16.0.tar.xz";
    };
    "0.17.0" = {
      version = "0.17.0";
      date = "2026-10-01";
      hash = "sha256-E5BfEZibZVZsVE0ZHUvFvV1vhY4wMgjPHS8JDl2RtRI=";
      url = "https://ziglang.org/download/0.17.0/zig-s390x-linux-0.17.0.tar.xz";
    };
  };
  builds = [
    {
      version = "0.17.0-dev.2329+1b7a78122";
      date = "2026-09-28";
      hash = "sha256-O/ytU0huESszBj7S/CpuhsFwEwHu+WDWbcZBj3eMhEk=";
      url = "https://ziglang.org/builds/zig-s390x-linux-0.17.0-dev.2329+1b7a78122.tar.xz";
    }
    {
      version = "0.17.0-dev.2338+b46a7f3a2";
      date = "2026-09-29";
      hash = "sha256-6WZ8xwJbMEOnO6Dbyer+TVFyFM3QkgirKf0jOFXTLgY=";
      url = "https://ziglang.org/builds/zig-s390x-linux-0.17.0-dev.2338+b46a7f3a2.tar.xz";
    }
    {
      version = "0.17.0-dev.2375+d8aab4878";
      date = "2026-09-30";
      hash = "sha256-pmW3Z/s9mk3ZuxYZW99LRtMl8cXun5Ua4ic9kzspOm8=";
      url = "https://ziglang.org/builds/zig-s390x-linux-0.17.0-dev.2375+d8aab4878.tar.xz";
    }
    {
      version = "0.17.0-dev.2384+ac77c23af";
      date = "2026-09-30";
      hash = "sha256-vjOvgZSanFWvtFEZrhn1e7085rEGgKfbpWfACFu32zE=";
      url = "https://ziglang.org/builds/zig-s390x-linux-0.17.0-dev.2384+ac77c23af.tar.xz";
    }
    {
      version = "0.17.0";
      date = "2026-10-01";
      hash = "sha256-E5BfEZibZVZsVE0ZHUvFvV1vhY4wMgjPHS8JDl2RtRI=";
      url = "https://ziglang.org/builds/zig-s390x-linux-0.17.0.tar.xz";
    }
  ];
}
