# Generated by `nix run .#update`; do not edit.
{
  releases = {
    "0.11.0" = {
      version = "0.11.0";
      date = "2023-08-04";
      hash = "sha256-dSYOhzJeggonjPnnTxMMez2EwLUZevsuPIXv8/zt1I0=";
      url = "https://ziglang.org/download/0.11.0/zig-linux-powerpc64le-0.11.0.tar.xz";
    };
    "0.12.0" = {
      version = "0.12.0";
      date = "2024-04-20";
      hash = "sha256-khi+7PuSUOnv+GP1j5h9ynB34yWN0mPEAmkIYSf5Z5s=";
      url = "https://ziglang.org/download/0.12.0/zig-linux-powerpc64le-0.12.0.tar.xz";
    };
    "0.12.1" = {
      version = "0.12.1";
      date = "2024-06-08";
      hash = "sha256-Ri1vEDUPPF1vxMnWz97ek9adAQOvAmiJoV9lxd55HTk=";
      url = "https://ziglang.org/download/0.12.1/zig-linux-powerpc64le-0.12.1.tar.xz";
    };
    "0.13.0" = {
      version = "0.13.0";
      date = "2024-06-07";
      hash = "sha256-akZ2IkSOgw6PhdIMq+0VFJivKwpi+HuMCDsv4SfmBBc=";
      url = "https://ziglang.org/download/0.13.0/zig-linux-powerpc64le-0.13.0.tar.xz";
    };
    "0.14.0" = {
      version = "0.14.0";
      date = "2025-03-05";
      hash = "sha256-PqvWCHbrwnSN6OtXtLjPp4hhupv3xt2D9OPh0nHXxF4=";
      url = "https://ziglang.org/download/0.14.0/zig-linux-powerpc64le-0.14.0.tar.xz";
    };
    "0.14.1" = {
      version = "0.14.1";
      date = "2025-05-21";
      hash = "sha256-FVI+dI79kiSuFkSC5cwfjBGwNSRrl0n7WwB1hITzhKE=";
      url = "https://ziglang.org/download/0.14.1/zig-powerpc64le-linux-0.14.1.tar.xz";
    };
    "0.15.1" = {
      version = "0.15.1";
      date = "2025-08-19";
      hash = "sha256-M54hBklr5wthTjLURCmCFuZ2w20I9c177j3R29RWf9c=";
      url = "https://ziglang.org/download/0.15.1/zig-powerpc64le-linux-0.15.1.tar.xz";
    };
    "0.15.2" = {
      version = "0.15.2";
      date = "2025-10-11";
      hash = "sha256-4YLF+NMPx/l9F9L/7xSIgmqjr6pR5fDb4UxZepi0V3g=";
      url = "https://ziglang.org/download/0.15.2/zig-powerpc64le-linux-0.15.2.tar.xz";
    };
    "0.16.0" = {
      version = "0.16.0";
      date = "2026-04-13";
      hash = "sha256-GIALRcCL9AszXKWrea6nCsoofKlpA26TgVV3K+yu6+s=";
      url = "https://ziglang.org/download/0.16.0/zig-powerpc64le-linux-0.16.0.tar.xz";
    };
  };
  builds = [
    {
      version = "0.17.0-dev.2329+1b7a78122";
      date = "2026-09-28";
      hash = "sha256-W+UPxtXAW76yvMReDWjwq9CVoM8tcCuLA6xTi0/6EmI=";
      url = "https://ziglang.org/builds/zig-powerpc64le-linux-0.17.0-dev.2329+1b7a78122.tar.xz";
    }
    {
      version = "0.17.0-dev.2338+b46a7f3a2";
      date = "2026-09-29";
      hash = "sha256-3FZyacY1ZOO/T4cGbQ9CX8tE2HKGwbfsAsrMskmvHvk=";
      url = "https://ziglang.org/builds/zig-powerpc64le-linux-0.17.0-dev.2338+b46a7f3a2.tar.xz";
    }
    {
      version = "0.17.0-dev.2375+d8aab4878";
      date = "2026-09-30";
      hash = "sha256-hUnZcxE46JfYvLZ8Y1SsoD0y59MuDGkmAw+oEuizHs8=";
      url = "https://ziglang.org/builds/zig-powerpc64le-linux-0.17.0-dev.2375+d8aab4878.tar.xz";
    }
  ];
}
