# Generated by `nix run .#update`; do not edit.
{
  releases = {
    "0.10.0" = {
      version = "0.10.0";
      date = "2022-10-31";
      hash = "sha256-KhJvNAGnp+/EtFTwqFwTPbGvWp3+4RfxciE7fL1Hv7o=";
      url = "https://ziglang.org/download/0.10.0/zig-linux-riscv64-0.10.0.tar.xz";
    };
    "0.10.1" = {
      version = "0.10.1";
      date = "2023-01-19";
      hash = "sha256-nbW1mlESuL65lQlLqADoiwBg6c98+t9Nw+ZmyQENx3s=";
      url = "https://ziglang.org/download/0.10.1/zig-linux-riscv64-0.10.1.tar.xz";
    };
    "0.11.0" = {
      version = "0.11.0";
      date = "2023-08-04";
      hash = "sha256-JKR4k37dtQfpbWC9TaAN6QkrPwkgGQ60XEyZyUawDtU=";
      url = "https://ziglang.org/download/0.11.0/zig-linux-riscv64-0.11.0.tar.xz";
    };
    "0.12.0" = {
      version = "0.12.0";
      date = "2024-04-20";
      hash = "sha256-uy0aeLAVlanAD/0uEqtG4y+LZ5j3auxkP/eOW09cWv0=";
      url = "https://ziglang.org/download/0.12.0/zig-linux-riscv64-0.12.0.tar.xz";
    };
    "0.12.1" = {
      version = "0.12.1";
      date = "2024-06-08";
      hash = "sha256-RjURqGOswWkRz/aAHel2I+beKWqrexXc2l9v0Hi0ALU=";
      url = "https://ziglang.org/download/0.12.1/zig-linux-riscv64-0.12.1.tar.xz";
    };
    "0.13.0" = {
      version = "0.13.0";
      date = "2024-06-07";
      hash = "sha256-n388aFiU/4D0Pq88rRWY9IRKxG9DCDdCN8f5EveQe7M=";
      url = "https://ziglang.org/download/0.13.0/zig-linux-riscv64-0.13.0.tar.xz";
    };
    "0.14.0" = {
      version = "0.14.0";
      date = "2025-03-05";
      hash = "sha256-orFNPeMm0/0JVUjvOL9aZ7FdrdYvvMkINtY8xDVfjvc=";
      url = "https://ziglang.org/download/0.14.0/zig-linux-riscv64-0.14.0.tar.xz";
    };
    "0.14.1" = {
      version = "0.14.1";
      date = "2025-05-21";
      hash = "sha256-AF8hT3Tbr7e02L0wX06dJQSPcR2exvp7PU/KF34RuII=";
      url = "https://ziglang.org/download/0.14.1/zig-riscv64-linux-0.14.1.tar.xz";
    };
    "0.15.1" = {
      version = "0.15.1";
      date = "2025-08-19";
      hash = "sha256-fKej5iFDb7MdZqJTEy/DlXShPSobTYRYr08ufG5DdP4=";
      url = "https://ziglang.org/download/0.15.1/zig-riscv64-linux-0.15.1.tar.xz";
    };
    "0.15.2" = {
      version = "0.15.2";
      date = "2025-10-11";
      hash = "sha256-STUSvcpIW+PGqbD2nctMvkWH86+OG+KC/dgnEIujmTA=";
      url = "https://ziglang.org/download/0.15.2/zig-riscv64-linux-0.15.2.tar.xz";
    };
    "0.16.0" = {
      version = "0.16.0";
      date = "2026-04-13";
      hash = "sha256-vAabDy9Wj1S6+9/B1lsS/Thu1qZSBEo3ruak9y8UB24=";
      url = "https://ziglang.org/download/0.16.0/zig-riscv64-linux-0.16.0.tar.xz";
    };
    "0.17.0" = {
      version = "0.17.0";
      date = "2026-10-01";
      hash = "sha256-GP8DKsbOz3RqhCWfZGMmTxMWD/iLw7gHIs4G+Uebgu0=";
      url = "https://ziglang.org/download/0.17.0/zig-riscv64-linux-0.17.0.tar.xz";
    };
    "0.6.0" = {
      version = "0.6.0";
      date = "2020-04-13";
      hash = "sha256-aN3uQ/dQPIrl8mqSHzYCw0cZoC7SJB9SjAuLiIzBSzg=";
      url = "https://ziglang.org/download/0.6.0/zig-linux-riscv64-0.6.0.tar.xz";
    };
    "0.7.0" = {
      version = "0.7.0";
      date = "2020-11-08";
      hash = "sha256-QN/4H6pvIyrECrv4i5Nx88yTK24JxCO5Q4fJ6lgMt74=";
      url = "https://ziglang.org/download/0.7.0/zig-linux-riscv64-0.7.0.tar.xz";
    };
    "0.7.1" = {
      version = "0.7.1";
      date = "2020-12-13";
      hash = "sha256-GHKUv9NZgzSMP+BCkBtC5n5+Nqt/d6X5adIcAFH00h8=";
      url = "https://ziglang.org/download/0.7.1/zig-linux-riscv64-0.7.1.tar.xz";
    };
    "0.8.0" = {
      version = "0.8.0";
      date = "2021-06-04";
      hash = "sha256-dZl1J6eM2rZMQMQ9nfOcAcTNtVe7OZKoaYODcaIEz+o=";
      url = "https://ziglang.org/download/0.8.0/zig-linux-riscv64-0.8.0.tar.xz";
    };
    "0.8.1" = {
      version = "0.8.1";
      date = "2021-09-06";
      hash = "sha256-St+vFHsCWRfAM2dGL+UBiqqe28ZDnvnNDaKwdK6WBVQ=";
      url = "https://ziglang.org/download/0.8.1/zig-linux-riscv64-0.8.1.tar.xz";
    };
    "0.9.0" = {
      version = "0.9.0";
      date = "2021-12-20";
      hash = "sha256-hUZt4HUEdn7Tf1l4JnKtQbvfQ9ZID6/Qf0VUMniwdiA=";
      url = "https://ziglang.org/download/0.9.0/zig-linux-riscv64-0.9.0.tar.xz";
    };
    "0.9.1" = {
      version = "0.9.1";
      date = "2022-02-14";
      hash = "sha256-II3qU2YsLFJ3e9njB2EV0hJqT3Gu1/L/O4/iJNw4gao=";
      url = "https://ziglang.org/download/0.9.1/zig-linux-riscv64-0.9.1.tar.xz";
    };
  };
  builds = [
    {
      version = "0.17.0-dev.2329+1b7a78122";
      date = "2026-09-28";
      hash = "sha256-naEb2/cCOf3NVCBLTdDdz9C89/gvS5sD2Z69HbDwLok=";
      url = "https://ziglang.org/builds/zig-riscv64-linux-0.17.0-dev.2329+1b7a78122.tar.xz";
    }
    {
      version = "0.17.0-dev.2338+b46a7f3a2";
      date = "2026-09-29";
      hash = "sha256-XA1lV7Y4MnEiudOrsURvJbk58+FDt5zuPB7ascw52gg=";
      url = "https://ziglang.org/builds/zig-riscv64-linux-0.17.0-dev.2338+b46a7f3a2.tar.xz";
    }
    {
      version = "0.17.0-dev.2375+d8aab4878";
      date = "2026-09-30";
      hash = "sha256-cy2uVOe03h5/1ee9slEx5hASdm2oy8Cvk2xqMiOmKcY=";
      url = "https://ziglang.org/builds/zig-riscv64-linux-0.17.0-dev.2375+d8aab4878.tar.xz";
    }
    {
      version = "0.17.0-dev.2384+ac77c23af";
      date = "2026-09-30";
      hash = "sha256-QIEx3unjrqvSmxgqDPiJKnZ3WGVNgIDj9tQ9/0Mrbvw=";
      url = "https://ziglang.org/builds/zig-riscv64-linux-0.17.0-dev.2384+ac77c23af.tar.xz";
    }
    {
      version = "0.17.0";
      date = "2026-10-01";
      hash = "sha256-GP8DKsbOz3RqhCWfZGMmTxMWD/iLw7gHIs4G+Uebgu0=";
      url = "https://ziglang.org/builds/zig-riscv64-linux-0.17.0.tar.xz";
    }
    {
      version = "0.18.0-dev.1+a6c6412a8";
      date = "2026-10-02";
      hash = "sha256-17c1iXeewGugePNoLyjePBbQNeLoTQv58GWNB6fr524=";
      url = "https://ziglang.org/builds/zig-riscv64-linux-0.18.0-dev.1+a6c6412a8.tar.xz";
    }
  ];
}
