# Generated by `nix run .#update`; do not edit.
{
  releases = {
    "0.10.0" = {
      version = "0.10.0";
      date = "2022-10-31";
      hash = "sha256-cgGy6JzXzC3eldOUhf19VkG6Z9xqmljANstMMI0ugt4=";
      url = "https://ziglang.org/download/0.10.0/zig-linux-armv7a-0.10.0.tar.xz";
    };
    "0.11.0" = {
      version = "0.11.0";
      date = "2023-08-04";
      hash = "sha256-rr6Lvso58T+bcwRGX5ruAasAXSQ4Nr1A9OyAgJPczJs=";
      url = "https://ziglang.org/download/0.11.0/zig-linux-armv7a-0.11.0.tar.xz";
    };
    "0.12.0" = {
      version = "0.12.0";
      date = "2024-04-20";
      hash = "sha256-tIIh9MZEFtJX8Pn3fYcn3M996Srqvll0TubnDWUKl7w=";
      url = "https://ziglang.org/download/0.12.0/zig-linux-armv7a-0.12.0.tar.xz";
    };
    "0.12.1" = {
      version = "0.12.1";
      date = "2024-06-08";
      hash = "sha256-J0k8ki/RRUE37Wy+a2vsADUoOPzTLm509PkYcBGBYVc=";
      url = "https://ziglang.org/download/0.12.1/zig-linux-armv7a-0.12.1.tar.xz";
    };
    "0.13.0" = {
      version = "0.13.0";
      date = "2024-06-07";
      hash = "sha256-SwVQI5ws2ITMA93rK5k0cI9LBzrVmpb8y/4J9+T1QjM=";
      url = "https://ziglang.org/download/0.13.0/zig-linux-armv7a-0.13.0.tar.xz";
    };
    "0.14.0" = {
      version = "0.14.0";
      date = "2025-03-05";
      hash = "sha256-pn2/qb33aSKOyZTyCYaYxhn5MIg8pe9jj1Du4td4jRA=";
      url = "https://ziglang.org/download/0.14.0/zig-linux-armv7a-0.14.0.tar.xz";
    };
    "0.14.1" = {
      version = "0.14.1";
      date = "2025-05-21";
      hash = "sha256-GzTZ7PrrOzYOhsC8Iz4aiiu+0tQPLU8gwSveIShxQyQ=";
      url = "https://ziglang.org/download/0.14.1/zig-armv7a-linux-0.14.1.tar.xz";
    };
    "0.6.0" = {
      version = "0.6.0";
      date = "2020-04-13";
      hash = "sha256-lGlpq+NX3vlcqcu/zr/PLZDPlnvNP0juh2YuMtkdjzU=";
      url = "https://ziglang.org/download/0.6.0/zig-linux-armv7a-0.6.0.tar.xz";
    };
    "0.7.0" = {
      version = "0.7.0";
      date = "2020-11-08";
      hash = "sha256-ARwmfiWpbuFgUFpWDEQdqgRTWanVDhOrG62p11yV2y0=";
      url = "https://ziglang.org/download/0.7.0/zig-linux-armv7a-0.7.0.tar.xz";
    };
    "0.7.1" = {
      version = "0.7.1";
      date = "2020-12-13";
      hash = "sha256-WgZi4HtMSWhmXh+XVY+Fkfb6zsRdLg/1cV5mF0MQfOs=";
      url = "https://ziglang.org/download/0.7.1/zig-linux-armv7a-0.7.1.tar.xz";
    };
    "0.8.0" = {
      version = "0.8.0";
      date = "2021-06-04";
      hash = "sha256-0AuL2Xt59F1vXalWmDuv6qCC5sKujG4cbU+qIvopsyA=";
      url = "https://ziglang.org/download/0.8.0/zig-linux-armv7a-0.8.0.tar.xz";
    };
    "0.8.1" = {
      version = "0.8.1";
      date = "2021-09-06";
      hash = "sha256-W6WBQYBeJRnzjPjnFZM8vwWfTz2t6Sxxg4zONBBF3gU=";
      url = "https://ziglang.org/download/0.8.1/zig-linux-armv7a-0.8.1.tar.xz";
    };
    "0.9.0" = {
      version = "0.9.0";
      date = "2021-12-20";
      hash = "sha256-UCJd7m5kSKY+6WODo02f47ujSujaGgyGGb3izfwd+H0=";
      url = "https://ziglang.org/download/0.9.0/zig-linux-armv7a-0.9.0.tar.xz";
    };
    "0.9.1" = {
      version = "0.9.1";
      date = "2022-02-14";
      hash = "sha256-beZEVstHV6VVgWYR6ml/hvunaB2No+GGP6cmpBfeSb4=";
      url = "https://ziglang.org/download/0.9.1/zig-linux-armv7a-0.9.1.tar.xz";
    };
  };
  builds = [
  ];
}
