# Generated by `nix run .#update`; do not edit.
{
  releases = {
    "0.10.0" = {
      version = "0.10.0";
      date = "2022-10-31";
      hash = "sha256-2sgTTxMoxQJp8+ULM0KY7HkWyzsO92kncD3dHJb9ARU=";
      url = "https://ziglang.org/download/0.10.0/zig-linux-i386-0.10.0.tar.xz";
    };
    "0.10.1" = {
      version = "0.10.1";
      date = "2023-01-19";
      hash = "sha256-jHEMpZZrEnsO4++6cxBgHuV6qz3WBSoILrxEbF77IxY=";
      url = "https://ziglang.org/download/0.10.1/zig-linux-i386-0.10.1.tar.xz";
    };
    "0.11.0" = {
      version = "0.11.0";
      date = "2023-08-04";
      hash = "sha256-ew3D4OBwrg4NIkCxiSr2ofn6rDUWyuJOV/eg57BGYqg=";
      url = "https://ziglang.org/download/0.11.0/zig-linux-x86-0.11.0.tar.xz";
    };
    "0.12.0" = {
      version = "0.12.0";
      date = "2024-04-20";
      hash = "sha256-+3UvzriHSagNYlpu/bI76oIIlitRUNbRTJLSDv2mKaU=";
      url = "https://ziglang.org/download/0.12.0/zig-linux-x86-0.12.0.tar.xz";
    };
    "0.12.1" = {
      version = "0.12.1";
      date = "2024-06-08";
      hash = "sha256-w2rAGcoPwxZ+UNF+Kv/T0HKgbFGXYXN9Bjmt/fLc/d0=";
      url = "https://ziglang.org/download/0.12.1/zig-linux-x86-0.12.1.tar.xz";
    };
    "0.13.0" = {
      version = "0.13.0";
      date = "2024-06-07";
      hash = "sha256-h2FZzB4V77Vx5hhDs5ojJ/iSWVHUi5p6AwSMNvchgPc=";
      url = "https://ziglang.org/download/0.13.0/zig-linux-x86-0.13.0.tar.xz";
    };
    "0.14.0" = {
      version = "0.14.0";
      date = "2025-03-05";
      hash = "sha256-VdG6Id5RCWhv+mdbnMHdZpMAk8ICmVpjfOPjl4FuTAg=";
      url = "https://ziglang.org/download/0.14.0/zig-linux-x86-0.14.0.tar.xz";
    };
    "0.14.1" = {
      version = "0.14.1";
      date = "2025-05-21";
      hash = "sha256-S85jR/oRIkdEPLCVLBnlYNH5C5EFBs+JX9B6e40cSnY=";
      url = "https://ziglang.org/download/0.14.1/zig-x86-linux-0.14.1.tar.xz";
    };
    "0.15.1" = {
      version = "0.15.1";
      date = "2025-08-19";
      hash = "sha256-3/Fm8l/dBug0HYMacSEbW6dBFGOmsmS976iGhDhpC2o=";
      url = "https://ziglang.org/download/0.15.1/zig-x86-linux-0.15.1.tar.xz";
    };
    "0.15.2" = {
      version = "0.15.2";
      date = "2025-10-11";
      hash = "sha256-TG4j852qMF4nQZe/3/DVb/0XUPwd4iauEFBcDv9S16U=";
      url = "https://ziglang.org/download/0.15.2/zig-x86-linux-0.15.2.tar.xz";
    };
    "0.16.0" = {
      version = "0.16.0";
      date = "2026-04-13";
      hash = "sha256-TjTiean4VjWN5CBJC1MZdMPTf483B+758DQuksFMMB8=";
      url = "https://ziglang.org/download/0.16.0/zig-x86-linux-0.16.0.tar.xz";
    };
    "0.17.0" = {
      version = "0.17.0";
      date = "2026-10-01";
      hash = "sha256-VeOeF1zVswmK/CnsR7JZATT1uHQXU2n7mue46DbXUxo=";
      url = "https://ziglang.org/download/0.17.0/zig-x86-linux-0.17.0.tar.xz";
    };
    "0.6.0" = {
      version = "0.6.0";
      date = "2020-04-13";
      hash = "sha256-qXovmuIVdXQ83XY8GRfUlADYP8Vi72RYKxi63kPrJM4=";
      url = "https://ziglang.org/download/0.6.0/zig-linux-i386-0.6.0.tar.xz";
    };
    "0.7.0" = {
      version = "0.7.0";
      date = "2020-11-08";
      hash = "sha256-S7IHLNNjvLHL60hy/1y8H2g7AtDMH5DEbj6nQizlMiI=";
      url = "https://ziglang.org/download/0.7.0/zig-linux-i386-0.7.0.tar.xz";
    };
    "0.7.1" = {
      version = "0.7.1";
      date = "2020-12-13";
      hash = "sha256-SILgUuX4NpC9AzS7T8FwK1QDyzo9KqY/19YEPYr+y6M=";
      url = "https://ziglang.org/download/0.7.1/zig-linux-i386-0.7.1.tar.xz";
    };
    "0.8.0" = {
      version = "0.8.0";
      date = "2021-06-04";
      hash = "sha256-luQ+5u2Bw8Y0AfRWvRxY7m1CNzpDyzJPXPSXTKCZiGU=";
      url = "https://ziglang.org/download/0.8.0/zig-linux-i386-0.8.0.tar.xz";
    };
    "0.8.1" = {
      version = "0.8.1";
      date = "2021-09-06";
      hash = "sha256-Lz6E8wSStfHF+XzswBZvB6io1Qxfhduzpu8qTub5FeY=";
      url = "https://ziglang.org/download/0.8.1/zig-linux-i386-0.8.1.tar.xz";
    };
    "0.9.0" = {
      version = "0.9.0";
      date = "2021-12-20";
      hash = "sha256-sNz2iDSSaMiDKSrN1V6qPBPXO5FG5LmQ+tlbhKKsUos=";
      url = "https://ziglang.org/download/0.9.0/zig-linux-i386-0.9.0.tar.xz";
    };
    "0.9.1" = {
      version = "0.9.1";
      date = "2022-02-14";
      hash = "sha256-53aET+zS5i/EDZRxiJEFeh28oYFv9gEzaemjjIdDdMo=";
      url = "https://ziglang.org/download/0.9.1/zig-linux-i386-0.9.1.tar.xz";
    };
  };
  builds = [
    {
      version = "0.17.0-dev.2329+1b7a78122";
      date = "2026-09-28";
      hash = "sha256-519PVEJEzS4zcgUK+wkzYTBUbrnZZ3B07klE26RtQFs=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.17.0-dev.2329+1b7a78122.tar.xz";
    }
    {
      version = "0.17.0-dev.2338+b46a7f3a2";
      date = "2026-09-29";
      hash = "sha256-H5tNc76E/La4HpJBvr1JO06ttqq5EVoPOQIvLtwjA/0=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.17.0-dev.2338+b46a7f3a2.tar.xz";
    }
    {
      version = "0.17.0-dev.2375+d8aab4878";
      date = "2026-09-30";
      hash = "sha256-Qj5RF99ZHW/etmLlo1pxmUvytYOx1zGtTiC/gAbxsGo=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.17.0-dev.2375+d8aab4878.tar.xz";
    }
    {
      version = "0.17.0-dev.2384+ac77c23af";
      date = "2026-09-30";
      hash = "sha256-IfzKLVYSSxSQJJQ96x7iSgahYxUhrFX1HCBiv89zi+A=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.17.0-dev.2384+ac77c23af.tar.xz";
    }
    {
      version = "0.17.0";
      date = "2026-10-01";
      hash = "sha256-VeOeF1zVswmK/CnsR7JZATT1uHQXU2n7mue46DbXUxo=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.17.0.tar.xz";
    }
    {
      version = "0.18.0-dev.1+a6c6412a8";
      date = "2026-10-02";
      hash = "sha256-0lYPPb7uA4QAxGlZjIN4kNjW5VBjQ9dNynjgLqmUBOg=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.18.0-dev.1+a6c6412a8.tar.xz";
    }
    {
      version = "0.18.0-dev.2+faa537cf9";
      date = "2026-10-03";
      hash = "sha256-p3yNu3g28Cx+s0ii+eQPFUqBH2fJoHnWVelP9VBCas4=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.18.0-dev.2+faa537cf9.tar.xz";
    }
    {
      version = "0.18.0-dev.4+5a23bf4b2";
      date = "2026-10-04";
      hash = "sha256-BFsws3G3YGrP7WWnVnFB2XZnbYzEXPwl2kBokXZhTbc=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.18.0-dev.4+5a23bf4b2.tar.xz";
    }
    {
      version = "0.18.0-dev.35+5e754304d";
      date = "2026-10-05";
      hash = "sha256-VlLtA7UXIYYYmESg7iiGmneWe/NqAcK1ZrRFnmRA2Og=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.18.0-dev.35+5e754304d.tar.xz";
    }
    {
      version = "0.18.0-dev.120+9fe22a29b";
      date = "2026-10-08";
      hash = "sha256-zFQTs3AtkoEOamMfNQ/0kxRYFCH0e7XQZLflAos6ifs=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.18.0-dev.120+9fe22a29b.tar.xz";
    }
    {
      version = "0.18.0-dev.131+41f885830";
      date = "2026-10-08";
      hash = "sha256-+9G8RSmSvHPZer/aKTiacv++DxOnvswbiLEiyhiDNNI=";
      url = "https://ziglang.org/builds/zig-x86-linux-0.18.0-dev.131+41f885830.tar.xz";
    }
  ];
}
