# Generated by `nix run .#update`; do not edit.
{
  releases = {
    "0.14.0" = {
      version = "0.14.0";
      date = "2025-03-05";
      hash = "sha256-MaLwffVfj1KLktVA25qubAs4ZDw03BrDOgER2FXplq4=";
      url = "https://ziglang.org/download/0.14.0/zig-linux-loongarch64-0.14.0.tar.xz";
    };
    "0.14.1" = {
      version = "0.14.1";
      date = "2025-05-21";
      hash = "sha256-/cNEeJvmvsviIL9a0DUVbmU8wUj02icBiMush3KfF+A=";
      url = "https://ziglang.org/download/0.14.1/zig-loongarch64-linux-0.14.1.tar.xz";
    };
    "0.15.1" = {
      version = "0.15.1";
      date = "2025-08-19";
      hash = "sha256-CvGKAS88TP++8pq19CAhSE2SUX+SGhOA+qzInFDB+J0=";
      url = "https://ziglang.org/download/0.15.1/zig-loongarch64-linux-0.15.1.tar.xz";
    };
    "0.15.2" = {
      version = "0.15.2";
      date = "2025-10-11";
      hash = "sha256-ldagPgQV2+MK6cANWLVEb9aB6/PUBEqLcH4XhMgHSmE=";
      url = "https://ziglang.org/download/0.15.2/zig-loongarch64-linux-0.15.2.tar.xz";
    };
    "0.16.0" = {
      version = "0.16.0";
      date = "2026-04-13";
      hash = "sha256-JQO+jsxZZfH3liRx0mfZ+D/LPML3/3isNAk7lyK76pM=";
      url = "https://ziglang.org/download/0.16.0/zig-loongarch64-linux-0.16.0.tar.xz";
    };
    "0.17.0" = {
      version = "0.17.0";
      date = "2026-10-01";
      hash = "sha256-WmAAuGYgHDs4ILVj/P0pZBGFOT59NQOeUCNdtBjYNnw=";
      url = "https://ziglang.org/download/0.17.0/zig-loongarch64-linux-0.17.0.tar.xz";
    };
  };
  builds = [
    {
      version = "0.17.0-dev.2329+1b7a78122";
      date = "2026-09-28";
      hash = "sha256-U2ct3tKIBE4EmSnAjS9/ZSrz/rTS+DLZK+inQbgmB/A=";
      url = "https://ziglang.org/builds/zig-loongarch64-linux-0.17.0-dev.2329+1b7a78122.tar.xz";
    }
    {
      version = "0.17.0-dev.2338+b46a7f3a2";
      date = "2026-09-29";
      hash = "sha256-n9U+9dH1sDNseNU+kiYYADy++CsLk3BXoS4emKOXK98=";
      url = "https://ziglang.org/builds/zig-loongarch64-linux-0.17.0-dev.2338+b46a7f3a2.tar.xz";
    }
    {
      version = "0.17.0-dev.2375+d8aab4878";
      date = "2026-09-30";
      hash = "sha256-dzlPkt3sjbXkVMUiBIPhQmT4kgZmQI1/YYT0GWAFYB0=";
      url = "https://ziglang.org/builds/zig-loongarch64-linux-0.17.0-dev.2375+d8aab4878.tar.xz";
    }
    {
      version = "0.17.0-dev.2384+ac77c23af";
      date = "2026-09-30";
      hash = "sha256-iFMBgpUnnRUCqKZl4hE6KaYFyn+i1pOfNjoP0lclJQM=";
      url = "https://ziglang.org/builds/zig-loongarch64-linux-0.17.0-dev.2384+ac77c23af.tar.xz";
    }
    {
      version = "0.17.0";
      date = "2026-10-01";
      hash = "sha256-WmAAuGYgHDs4ILVj/P0pZBGFOT59NQOeUCNdtBjYNnw=";
      url = "https://ziglang.org/builds/zig-loongarch64-linux-0.17.0.tar.xz";
    }
    {
      version = "0.18.0-dev.1+a6c6412a8";
      date = "2026-10-02";
      hash = "sha256-lmtszNWDqZomrciXuqGmySiLGpFii71O6BHA0hOLx9c=";
      url = "https://ziglang.org/builds/zig-loongarch64-linux-0.18.0-dev.1+a6c6412a8.tar.xz";
    }
    {
      version = "0.18.0-dev.2+faa537cf9";
      date = "2026-10-03";
      hash = "sha256-PDVOmeI/7GjyQ7l9UE9mnLMMFR8PYydShhWgw5ChDwE=";
      url = "https://ziglang.org/builds/zig-loongarch64-linux-0.18.0-dev.2+faa537cf9.tar.xz";
    }
    {
      version = "0.18.0-dev.4+5a23bf4b2";
      date = "2026-10-04";
      hash = "sha256-AqPvXbxdOgJljBXERgu76hH0u/SrK9Y0XCUO+fLql5Q=";
      url = "https://ziglang.org/builds/zig-loongarch64-linux-0.18.0-dev.4+5a23bf4b2.tar.xz";
    }
    {
      version = "0.18.0-dev.35+5e754304d";
      date = "2026-10-05";
      hash = "sha256-BEsMh7vzbfe58dPjopuMypCc2C36wJmJBMiMMw8IZss=";
      url = "https://ziglang.org/builds/zig-loongarch64-linux-0.18.0-dev.35+5e754304d.tar.xz";
    }
  ];
}
