version = 1

[[annotations]]
path = "flake.lock"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "mirrors.json"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "sources.json"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
