on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: nixos
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: ./update
      - run: "git config user.email git@git.ocjtech.us"
      - run: "git config user.name git"
      - run: "git add -A"
      - run: "git commit -m 'update sources.json' || true"
      - run: "git push -u origin main"
