on:
  - push
  - pull_request
name: Test
jobs:
  test:
    runs-on: nixos
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: nix flake check
      - run: ./update
