# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  fetchgit,
  fetchurl,
  fetchzip,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
  # Accepted and ignored. Expressions from zon2nix before 0.8 built the
  # packages with `linkFarm`, and some callers override it with a version that
  # copies, to work around Zig mishandling symlinked package directories
  # (https://codeberg.org/ziglang/zig/issues/32121). The packages are real
  # directories now, so the override is not needed, and is taken here only so
  # that passing it is not an error.
  linkFarm ? null,
}:
let
  # A git repository, checked out the way Zig reads it: every file as
  # committed. An ordinary checkout applies the repository's `.gitattributes`,
  # which can rewrite a file's line endings or run it through a filter, and
  # the package would then no longer match its hash. Pointing git at its
  # built-in empty tree for attributes turns them all off, and `core.autocrlf`
  # is turned off too, since it converts line endings even without them.
  # zon2nix computes the hash with exactly these settings.
  fetchZigGit =
    args:
    fetchgit (
      args
      // {
        fetchSubmodules = false;
        preFetch = ''
          export GIT_ATTR_SOURCE=4b825dc642cb6eb9a060e54bf8d69288fbee4904
          export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.autocrlf GIT_CONFIG_VALUE_0=false
        '';
      }
    );

  # Every package, by the hash Zig knows it by, as Nix fetches it.
  packages = {
    "datetime-0.0.1-6-va70MhRQAoQi0NvxUHRez3_PcVc3-Sz702lZwzTH4G" = fetchZigGit {
      name = "datetime";
      url = "https://git.jcollie.dev/jeff/zig-datetime.git";
      rev = "96f8d4a6946b89b68b8c5eeb6f274647662c6aa9";
      hash = "sha256-cRzFz64J0y1zqVDVCNxgfapW/8Bx2xC9WbWZLeCgvMA=";
    };
    "dns-0.1.0-vMrSfh8OBwDpnEuJqpxJOwv7ofpQKnDGfDjQfZ6VV6P7" = fetchZigGit {
      name = "dns";
      url = "https://git.jcollie.dev/jeff/zig-dns.git";
      rev = "6027a64a3fbc84b146ac05306d0fa25f837fdcba";
      hash = "sha256-Rg+KD4/lra4hLXu9dx+cyqLCnUrpkrT03dCyj34IU5I=";
    };
    "dns_client-0.1.0-L4NvbmzfDwDTyDCVrpZSZzB0HjLLr7Tvtg8VsSO4OBKD" = fetchZigGit {
      name = "dns_client";
      url = "https://git.jcollie.dev/jeff/zig-dns-client.git";
      rev = "ef4f807b314188d17de80cfe389822f4ee3b8dd1";
      hash = "sha256-ZYuzfUIFap+Sr0jhQ2m+8dG3vDQ/fHkAfCaCCPnNh4I=";
    };
    "dns_zone-0.1.0-EGC_DMHNBAD7w62XBCItDkzhdCnIEEAjA-j979AP8s26" = fetchZigGit {
      name = "dns_zone";
      url = "https://git.jcollie.dev/jeff/zig-dns-zone.git";
      rev = "c22cf377a4da4dd657bbd8736b0aeb5968824223";
      hash = "sha256-sjusPeYssDG24NkRZB9lJC68/C6kNsOZev1nH9BFsG0=";
    };
    "http-0.0.0-e28mQF3GFwCopCpB0NHRvhDpx-7MFNy5qsvah8Nsgda6" = fetchZigGit {
      name = "http";
      url = "https://git.jcollie.dev/jeff/zig-http.git";
      rev = "8aaed5d468dabc65119710ad11302f9f76567593";
      hash = "sha256-ZLpGBgu6gm/2y80bycNZENh6y3FMb9D62uKiYQSFzy4=";
    };
    "http-0.0.0-e28mQNVIGQB3-ksVltDG1Y9ENZ_mV-EwaVhmqfDF5ad1" = fetchZigGit {
      name = "http";
      url = "https://git.jcollie.dev/jeff/zig-http.git";
      rev = "ad62ed86e5b8466bac032ca0b24f6f3b7dce9fa8";
      hash = "sha256-3iOc7/h4Jct8noLYgFjP9vTSYAesnoCfDjYVXlYqTRc=";
    };
    "zig_quic-0.0.0-4oF4nixaHAAStQVlMC752k56jV2VIbwVRzBxqXgLB774" = fetchZigGit {
      name = "quic";
      url = "https://git.jcollie.dev/jeff/zig-quic.git";
      rev = "47ec653a56df0275d4f05e2e31da81f43ad93abf";
      hash = "sha256-TzBvPBaeY60MyaoGIssdbV3rt+LmZVuPFFGgysCQT3c=";
    };
    "std_crypto_ext-0.0.0-zmlw4Y45BQB24pSysBQZIFKu-2epohsc-oHri-5jc1_z" = fetchZigGit {
      name = "std_crypto_ext";
      url = "https://git.jcollie.dev/jeff/zig-std-crypto-ext.git";
      rev = "ed9b3a9a7249e78731e770e251130f99c1ab70b7";
      hash = "sha256-1F9y41VSbKMenGvcbkazXfWjohNZMP2KqTIzYyQWQaY=";
    };
    "tls-0.1.0-ER2e0pV5CQCwe6a-c0KHPP-Z3sattGdSLH2upYTHCpBn" = fetchZigGit {
      name = "tls";
      url = "https://git.jcollie.dev/jeff/tls.zig.git";
      rev = "05587bbef303c8e9504fec7d07daeead1d597071";
      hash = "sha256-55wLBBh1A6CFBROoA7PYwJZMNYsb6VS62faF5cEP0MU=";
    };
    "N-V-__8AABybDwDd46ZHFqBjb0twea7p9vwNzdSzUHFwA55f" = fetchurl {
      url = "https://data.iana.org/time-zones/releases/tzcode2026d.tar.gz";
      hash = "sha256-L1yff+Kea4y4Y1g2Z4hLjOF7CkhTVaBUtZHGvfzYF5E=";
    };
    "N-V-__8AAFiAFQDNovBNmFwF3hznlSfpY7KwAN3Jy7rhie29" = fetchurl {
      url = "https://data.iana.org/time-zones/releases/tzdata2026d.tar.gz";
      hash = "sha256-DLKqjjM8PcBJutxCoMYfIZh7jNROEH+pALrXZKrMd2c=";
    };
    "uri-0.1.0-yCrwNNH2EwBMp75OiyjnW1w5FMiFdI0gWghu4QMEVWtU" = fetchZigGit {
      name = "uri";
      url = "https://git.jcollie.dev/jeff/zig-uri.git";
      rev = "c472509ef662a1528f24e283799280bebbeb2777";
      hash = "sha256-76g/TqOdvh97UfcNN2FrnrTnV0VQZ3Y5fRnfB5hoqWw=";
    };
    "uucode-0.2.0-ZZjBPh-6VADBlunHbwABTPng0DH6uJqd4CvvtjZ19tny" = fetchZigGit {
      name = "uucode";
      url = "https://github.com/jacobsandlund/uucode";
      rev = "61e54266895f833b307de81a0e3038cf1f1bebd4";
      hash = "sha256-6Riz1CowKgQr70YAcfozHETUqfOR4gYIwUE5txjX70o=";
    };
    "z46-0.1.0-_AxhwCThCQCYrGgJUgyc2Ozk5i4fwCkmimRXMxmNDPgc" = fetchZigGit {
      name = "z46";
      url = "https://git.jcollie.dev/jeff/z46.git";
      rev = "12de8fc8e77f3d857ea90d1c10fd78c3abdf05a6";
      hash = "sha256-cZR+YgslD5dmps3wRjZcfoyPniDN3X+KEfPY+5vNT1w=";
    };
    "z46-0.1.0-_AxhwMFJBABjD8e-JzV-E1BvOHFiztBY2Wok_amuD5lp" = fetchZigGit {
      name = "z46";
      url = "https://git.jcollie.dev/jeff/z46.git";
      rev = "d05a48954e7ca231cfc619f24a70a24333f3324e";
      hash = "sha256-3yDaarVqWbvV3K42Bqp7Wrvm55yi+TbYYCxg+tm5YEw=";
    };
    "win32-42.0.39-preview-mX5pFS564gPTezZn4v3TMxRnfJUrZNx1B_F2p2HKXOeG" = fetchZigGit {
      name = "zigwin32";
      url = "https://github.com/marlersoft/zigwin32";
      rev = "9f15c276b4e9d05afd34a10d8662a7dfc34647ea";
      hash = "sha256-JCmUrieEnOKQViUGjPNrlGwJMMM4X/BjC3iur5fRbqA=";
    };
    "zqlite-0.0.1-RWLaY8M8nAB4m0tlSpT9A5PGUwX_JfWC5VlPjLe7lG2Q" = fetchZigGit {
      name = "zqlite";
      url = "https://github.com/karlseguin/zqlite.zig";
      rev = "b519eea9b1a2b5fcad68af6d0629e717e8746684";
      hash = "sha256-BzcP6S0LqfpRHFvoaz3fdcFiWfA+zZFBiQ/WjwkojDo=";
    };
  };

  # The packages whose own manifest declares a dependency by `.path`. Zig
  # 0.16.0 cannot build these through `zig build --system`: it spins in
  # userspace forever, because a `.path` dependency's hash is computed against
  # the system package directory during the fetch and against the real global
  # cache afterwards, and in that mode the two disagree. A package that wants
  # `--system` copies each of these into its build root and passes `--fork=`;
  # see the README.
  pathDependencyPackages = [
  ];
in
# One directory holding every package the way Zig unpacks it -- filtered by
# its manifest's `.paths` and checked against its hash -- which is what
# `zig build --system` wants.
#
# They have to be real directories holding real files, not links into each
# package's own store path. Zig runs a dependency's build steps from inside
# it and counts its way back out through `..`, which lands in the wrong place
# when the directory is a symlink; and `installHeadersDirectory` copies only
# what the directory walk calls a file, so symlinked headers are skipped
# without a word. Building them all in one derivation gives real files from
# the start, without a second copy of everything.
runCommandLocal name
  {
    nativeBuildInputs = [ zig_0_16 ];
    passthru = { inherit pathDependencyPackages; };
  }
  ''
    mkdir "$out"

    # Each package gets a directory of its own to work in, since `zig fetch`
    # leaves what it unpacked in `zig-pkg/` under the directory it ran in.
    unpack() {
      local work="$TMPDIR/work/$1"
      mkdir -p "$work/src" "$work/cache/tmp"
      # workaround https://codeberg.org/ziglang/zig/issues/31866
      # https://github.com/Cloudef/zig2nix/issues/54
      touch "$work/src/build.zig"
      # `zig fetch` recompresses every package into `p/` at gzip level 9 for
      # its own cache, which is nearly all of its time and of no use here.
      # With `p` a file rather than a directory that step fails at once --
      # Zig warns, and carries on -- and the package is left in `zig-pkg/`.
      touch "$work/cache/p"

      local hash
      if ! hash="$(cd "$work/src" && zig fetch --global-cache-dir "$work/cache" "$2" 2>"$work/log")"; then
        cat "$work/log" >&2
        return 1
      fi
      if [ "$hash" != "$1" ]; then
        echo "$2 is $hash to Zig, not $1" >&2
        return 1
      fi
      mv "$work/src/zig-pkg/$1" "$out/$1"
      rm -rf "$work"
    }
    export -f unpack

    # Several at a time: `zig fetch` spends most of a package on one core.
    cores="''${NIX_BUILD_CORES:-0}"
    if [ "$cores" -le 0 ]; then cores="$(nproc)"; fi
    xargs -P "$cores" -n 2 bash -c 'unpack "$@"' unpack <<'EOF'
    ${lib.concatStrings (lib.mapAttrsToList (hash: src: "${hash} ${src}\n") packages)}
    EOF
  ''
